version: "3.8"

services:
  localstack:
    container_name: "localstack_free_demo"
    # Going back to a 100% open-source legacy version
    image: localstack/localstack:1.4.0
    ports:
      - "0.0.0.0:4566:4566"
    environment:
      - SERVICES=s3,lambda,cloudwatch,iam,sts
      - DEBUG=1
      - LAMBDA_EXECUTOR=local
      - DISABLE_CORS_CHECKS=1
      - EXTRA_CORS_ALLOWED_ORIGINS=*
    restart: "no"
